

class Gym:
    """
    Main module responsible for training
    """

    def __init__(self):
        pass

    def train(self, csv_file, automatic_search=True, models=None, minimum_score=0.7):
        """
        Trains input data by automatic_search (GA) or with given models
        :param csv_file: multi-currency features csv file (for example generated by blueprint module)
        :param automatic_search: automatically find the best models
        :param models: list of models to be used. If automatic_search is True, models will be included into model search
        :param minimum_score: minimum_score the model needs to have so that it is returned
        :return: list of best models with their score
        """
        pass



